Repository Woynert/buenavida-front, pull requests merged in 2022-11, with the labels that each got.

#33 Field Check: User Registration
  angular.json
  src/app/app.module.ts
  src/app/layout/view-login/view-login.component.css
  src/app/layout/view-login/view-login.component.html
  src/app/layout/view-login/view-login.component.ts
  src/app/layout/view-signin/view-signin.component.css
  src/app/layout/view-signin/view-signin.component.html
  src/app/layout/view-signin/view-signin.component.ts
  src/app/service/captcha.service.spec.ts
  src/app/service/captcha.service.ts
Labels: Sesión

#36 Vitrina con filtros y barra superior de navegación
  src/app/app.component.css
  src/app/app.component.html
  src/app/app.module.ts
  src/app/layout/view-vitrina/view-vitrina.component.css
  src/app/layout/view-vitrina/view-vitrina.component.html
  src/app/layout/view-vitrina/view-vitrina.component.ts
  src/app/layout/view-vitrina/vitrina-filter/vitrina-filter.component.css
  src/app/layout/view-vitrina/vitrina-filter/vitrina-filter.component.html
  src/app/layout/view-vitrina/vitrina-filter/vitrina-filter.component.ts
  src/app/layout/view-vitrina/vitrina-pager/vitrina-pager.component.css
  src/app/layout/view-vitrina/vitrina-pager/vitrina-pager.component.html
  src/app/layout/view-vitrina/vitrina-pager/vitrina-pager.component.spec.ts
  src/app/layout/view-vitrina/vitrina-pager/vitrina-pager.component.ts
  src/app/service/search.service.ts
  src/app/shared/header/header.component.css
  src/app/shared/header/header.component.html
  src/app/shared/header/header.component.ts
  src/app/shared/interface.ts
  src/assets/icon/bag-plus-fill.svg
  src/assets/icon/basket3.svg
  src/assets/icon/check-lg.svg
  src/assets/icon/dash.svg
  src/assets/icon/heart-fill.svg
  src/assets/icon/heart.svg
  src/assets/icon/lock.svg
  src/assets/icon/person-circle.svg
  src/assets/icon/person-fill.svg
  src/assets/icon/person-plus-fill.svg
  src/assets/icon/search.svg
  src/assets/icon/x.svg
  src/assets/logo.jpg
Labels: Vitrina, Barra navegacion

#39 Menu my account
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/layout/view-login/view-login.component.css
  src/app/layout/view-login/view-login.component.html
  src/app/layout/view-signin/view-signin.component.css
  src/app/layout/view-signin/view-signin.component.html
  src/app/layout/view-vitrina/view-vitrina.component.css
  src/app/layout/view-vitrina/vitrina-filter/vitrina-filter.component.css
  src/app/layout/view-vitrina/vitrina-pager/vitrina-pager.component.css
  src/app/shared/header/header.component.css
  src/app/shared/header/header.component.html
  src/app/shared/header/header.component.ts
  src/assets/icon/envelope-fill.svg
Labels: Barra navegacion, Modal

#41 Modal cart and Page cart
  src/app/layout/view-cart/view-cart.component.css
  src/app/layout/view-cart/view-cart.component.html
  src/app/layout/view-cart/view-cart.component.ts
  src/app/layout/view-vitrina/view-vitrina.component.html
  src/app/layout/view-vitrina/view-vitrina.component.ts
  src/app/service/cart.service.ts
  src/app/shared/ProductsCart.ts
  src/app/shared/header/header.component.css
  src/app/shared/header/header.component.html
  src/app/shared/header/header.component.ts
  src/assets/icon/trash-fill.svg
Labels: Carrito, Barra navegacion, Modal

#44 Session check & Favorite toggle
  angular.json
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/layout/view-login/view-login.component.ts
  src/app/layout/view-vitrina/view-vitrina.component.css
  src/app/layout/view-vitrina/view-vitrina.component.html
  src/app/layout/view-vitrina/view-vitrina.component.ts
  src/app/service/favorites.service.ts
  src/app/service/session.service.ts
  src/app/service/token.service.spec.ts
  src/app/service/token.service.ts
  src/app/shared/interface.ts
  src/environments/environment.ts
Labels: Sesión, Vitrina, Favoritos

#48 Modal product & Favorites in vitrina
  src/app/app.component.ts
  src/app/layout/view-vitrina/modal-product.css
  src/app/layout/view-vitrina/view-vitrina.component.html
  src/app/layout/view-vitrina/view-vitrina.component.ts
  src/app/service/cart.service.ts
  src/app/service/favorites.service.ts
  src/app/shared/header/header.component.html
  src/app/shared/header/header.component.ts
  src/app/shared/interface.ts
Labels: Vitrina, Modal, Favoritos

#49 css all page
  src/app/layout/view-cart/view-cart.component.css
  src/app/layout/view-login/view-login.component.css
  src/app/layout/view-signin/view-signin.component.css
  src/app/layout/view-vitrina/modal-product.css
  src/app/layout/view-vitrina/view-vitrina.component.css
  src/app/layout/view-vitrina/view-vitrina.component.html
  src/app/layout/view-vitrina/vitrina-filter/vitrina-filter.component.css
  src/app/layout/view-vitrina/vitrina-pager/vitrina-pager.component.css
  src/app/shared/header/header.component.css
  src/app/shared/header/header.component.html
  src/styles.css
Labels: Sesión
